### ISSUE TITLE
getFromBag() metodu set edilməyən keyi yazdıqda null qaytarır

### ISSUE THREAD

**Issue by etercode** [mesolaries/SmartApiBundle#1]
Məsələn mən $smart->getFromBag() vasitəsilə set etmədiyim key-i götürüb hansısa obyektə əlavə etsəm, database-ə həmişə null gedəcək xəbərim olmayacaq ki, set etmemisem. Ona görə null əvəzinə exception qaytarsaz daha yaxşı olardı.

**Comment by mesolaries** [comment]
Fixed with mesolaries@158b9973
